### ISSUE TITLE
Bad performance under Windows

### ISSUE THREAD

**Issue by kslstn** [KKBOX/FireApp#267]
For just one project (a WordPress theme), fire.app 1.33.1  takes up around 16% CPU. Live reload is too slow to be of use: it takes over 7 seconds to pick up on changes. When I have fire.app compile css from scss too, it is around 17 seconds. The scss extension for Sublime Text as well as the Scout application only take 4.2 seconds to compile the css, so there seems to be something wrong here.

Edit: I'm running Windows 8.1 on a Intel Core i702670QM @2.2GHz

**Comment by hlb** [comment]
the performance issue should be fixed in 1.14
