### ISSUE TITLE
Windows下使用 fire.app v1.13.1 (使用compass + susy) 編譯速度非常慢, java 1.8會有此問題

### ISSUE THREAD

**Issue by fdjkgh580** [KKBOX/FireApp#280]
當我在windows 底下使用
import "susy";
import "compass/css3";
並配合
.container {
    @include border-radius(10px); 
   //......... x1000 次
}

編譯起來超過十秒，超誇張....
試過windows8 跟 windows7一樣都有這個問題。

之前前一版，fire.app v1.12 沒有這個問題。
但升級到 1.13 就跑得很慢。

**Comment by hlb** [comment]
the performance issue should be fixed in 1.14
