### ISSUE TITLE
Long compile time

### ISSUE THREAD

**Issue by josfaber** [KKBOX/FireApp#288]
Fire takes about 9 seconds after save from editor before I see the change notification and the css is compiled. Cannot figure out what causes it. Setup is latest mbp, compiling 6 scss files with this config:

css_dir = "css" # by Fire.app 
sass_dir = "scss" # by Fire.app 
images_dir = "images" # by Fire.app 
javascripts_dir = "js" # by Fire.app 
fireapp_coffeescripts_dir = "coffeescripts" # by Fire.app 
fireapp_livescripts_dir = "livescripts" # by Fire.app 
fireapp_minifyjs_on_build = false # by Fire.app 
fireapp_always_report_on_build = false # by Fire.app 
output_style = :compressed # by Fire.app 
relative_assets = false # by Fire.app 
line_comments = false # by Fire.app 
sass_options = {:debug_info=>false} # by Fire.app 
fireapp_coffeescript_options = {:bare=>false} # by Fire.app 
fireapp_livescript_options = {:bare=>false} # by Fire.app

**Comment by hlb** [comment]
@josfaber the v 1.14 should be faster
