### ISSUE TITLE
fireapp-documents-teaching-material <%= livereload_js %> does not work as described in Fire.app Feature Tutorial 

### ISSUE THREAD

**Issue by PlumHunter** [KKBOX/FireApp#292]
I am following your online tutorial. I am on the "Using Template Helpers" page.
It instructs "After modifying the file name, add a helper to generate LiveReload-js before </body>
1. <%= livereload_js %>". I have the renamed file screenshots.html.erb in my C:\Sass Fire\fireapp-documents-teaching-material folder. That folder was created by unzipping the fireapp-documents-teaching-material zip file. I have the fire-app application in folder named C:\Sass Fire\fire.app.
The tutorial goes on to say : "Refresh the browser to active the added JavaScripts. Now, the browser will automatically refresh after modifying files." After changing files, nothing happened - the browser did not reflect the changes. It also had this error at the top of the page in the browser : "Errno::ESRCH: No such process - No message available". I am giving up on this tutorial and fire.app altogether and go back to using compass.app. I am following the tutorial and getting nowhere - a waste of my time and money. Did you guys actually go thru the tutorial to make sure it works and document potential difficulties??? What a (*&^(*&^(*&^(*&^ waste!!!!!

**Comment by hlb** [comment]
livereload-related issue has been fixed in v1.14
