### ISSUE TITLE
Crash Error: undefined method 'to_tree' for nil:NilClass

### ISSUE THREAD

**Issue by wikirex** [KKBOX/FireApp#293]
Hi, 
I kept getting this error message around every 10 mins and the app just stopped.
I need to restart the app and watch a folder over and over again.
Please refer to attached image for details. Any suggestions?
Thanks.
![fireapp_error](https://cloud.githubusercontent.com/assets/5335568/6593350/dae1df34-c812-11e4-8c39-9c47812b40b4.png)

**Comment by PlumHunter** [comment]
I paid for fire.app but could not get their tutorial examples to work at
all. I spent $14 for a piece of crap. I use compass.app from within
Netbeans ide - works great. I posted an issue on the github issues page -
they did not have the decency to reply ...

**Comment by hlb** [comment]
@wikirex @PlumHunter hello, we have beta version, which should fix this version. Please mail to contact@kktix.com to get one.

**Comment by hlb** [comment]
confirm fixed.
