### ISSUE TITLE
LiveReload無法與Chrome同時更新。

### ISSUE THREAD

**Issue by EricChen70135** [KKBOX/FireApp#299]
LiveReload沒有啟動

**Comment by hlb** [comment]
可以說明清楚你遇到的問題嗎？ :)

**Comment by EricChen70135** [comment]
Fire.app內建的LiveReload無法與Chrome的擴充功能的LiveReload同步，必須還要使用Commend+R重新整理(Mac)

**Comment by hlb** [comment]
@EricChen70135 請問您安裝的 LiveReload 版本是 2.0.9 嗎？

**Comment by EricChen70135** [comment]
目前我安裝的LiveReload的版本是2.1.0了

**Comment by hlb** [comment]
@EricChen70135 我這邊 Compass.app 搭配 2.0.9 是正常的。請問你的目錄有中文或是特殊的目錄名稱結構嗎？

**Comment by EricChen70135** [comment]
找到原因了！原來是中文的關係，我先前用比較舊的Fire.app版本，比較不會有這個問題，謝謝你！

**Comment by hlb** [comment]
@EricChen70135 太好了。抱歉我們用 Java + JRuby 對多國語言的支援很差，還在等它修好 :-/

**Comment by EricChen70135** [comment]
沒關係有解決問題就好，非常謝謝你。
