### ISSUE TITLE
Watch multiple projekt to compile

### ISSUE THREAD

**Issue by ClemensSahs** [KKBOX/FireApp#300]
hello i have a really short question,

will it possible to watch multiple project?

**Comment by hlb** [comment]
no

**Comment by ClemensSahs** [comment]
Is there any reason or some explanation, the this can not be a future Feature?

**Comment by hlb** [comment]
@ClemensSahs sorry for the short reply above (was too busy). Fire.app is a modified version of [Serve](http://get-serve.com/) container with GUI, so we have to rewrite the whole program to support multiple projects.
