### ISSUE TITLE
How can i install Fireapp without email link

### ISSUE THREAD

**Issue by renaudMaupoux** [KKBOX/FireApp#303]
Hello I bought FireApp one week ago on Paypal and I think I deleted email to install FireApp by mistake
How can I do to download it. Thanks

**Comment by hlb** [comment]
@renaudMaupoux please mail to fireapp@kkbox.com, and tell us your PayPal email address or order number :)

**Comment by Frontend-Head** [comment]
Same problem here! 
I bought the fireapp and the compassapp.
I send u a mail to fireapp@kkbox.com and compassapp@kkbox.com with my email address and order numer but i dont get any answers!!!

**Comment by hlb** [comment]
@Frontend-Head hello, we have resent you the download link, please check :)
