### ISSUE TITLE
Buy FireApp in bulk?

### ISSUE THREAD

**Issue by selfthinker** [KKBOX/FireApp#304]
Is it possible to buy Fire.app in bulk? Right now it seems if I'd like to buy e.g. 50, I would need to buy them one by one. :-/
When you get to the PayPal page there is "Quantity: 1" on the top left corner, which makes me think PayPal might have an option to let the user increase that number?

I know I don't necessarily *need* to buy them multiple times, I could just pay once and then distribute the download among colleagues. But I'm planning to introduce Fire.app to my company and we would like to support the Open Source community and pay for the tool properly.

**Comment by hlb** [comment]
@selfthinker thank you very much :heart: 

* You can consider to donate UMDF since Compass is a charityware, and we use Compass as core http://umdf.org/compass
* You can try https://transactions.sendowl.com/cart?merchant_id=48 to buy multiple copies :)

**Comment by hlb** [comment]
Sorry, link fixed. should be https://transactions.sendowl.com/packages/393/C893C6AF/add_to_cart

**Comment by selfthinker** [comment]
Unfortunately our company doesn't have a PayPal account (and apparently it requires lots of paperwork to get one in our case). But I hope your reply here hasn't been in vain and others will be using it.
Some of us will probably buy Fire.app privately and claim the expenses back from our company. Unless there is another way to pay?

**Comment by hlb** [comment]
We only provide PayPal, but thank you anyway :)
