### ISSUE TITLE
"Build Project" doesn't build assets, 500 error

### ISSUE THREAD

**Issue by selfthinker** [KKBOX/FireApp#306]
When I use "Build Project" I get a 500 error (the very same error both on OS X and on Windows 7). All the HTML files build fine but there are no assets, not even the folders are there.
As a workaround I can just copy the asset folders manually over (because they were already correctly compiled while I was watching the project) and it works. But it doesn't work automatically, I guess due to that error.

```
500 Internal Server Error 
/Applications/Fire.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:346:in `open_http'
/Applications/Fire.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:776:in `buffer_open'
/Applications/Fire.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:203:in `open_loop'
org/jruby/RubyKernel.java:1270:in `catch'
/Applications/Fire.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:201:in `open_loop'
/Applications/Fire.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:146:in `open_uri'
/Applications/Fire.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:678:in `open'
/Applications/Fire.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:33:in `open'
file:/Applications/Fire.app/Contents/Java/fire-app.jar!/project_builder.rb:209:in `write_dynamaic_file'
org/jruby/RubyIO.java:1181:in `open'
file:/Applications/Fire.app/Contents/Java/fire-app.jar!/project_builder.rb:209:in `write_dynamaic_file'
file:/Applications/Fire.app/Contents/Java/fire-app.jar!/project_builder.rb:112:in `build_html'
org/jruby/RubyDir.java:245:in `glob'
file:/Applications/Fire.app/Contents/Java/fire-app.jar!/project_builder.rb:91:in `build_html'
file:/Applications/Fire.app/Contents/Java/fire-app.jar!/project_builder.rb:180:in `build'
file:/Applications/Fire.app/Contents/Java/fire-app.jar!/ui/tray.rb:437:in `build_project_handler'
file:/Applications/Fire.app/Contents/Java/fire-app.jar!/app.rb:229:in `try'
file:/Applications/Fire.app/Contents/Java/fire-app.jar!/ui/tray.rb:425:in `build_project_handler'
anon_class362714665_442972437.gen:13:in `handleEvent'
file:/Applications/Fire.app/Contents/Java/fire-app.jar!/ui/tray.rb:83:in `run'
file:/Applications/Fire.app/Contents/Java/fire-app.jar!/main.rb:129:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
/Applications/Fire.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
/Applications/Fire.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by hlb** [comment]
@selfthinker can you link to the web server by Fire.app http://localhost:24681 ?

**Comment by encosion** [comment]
On a related note, not all dependencies are making it through to the build. Not the "img" sub folder is missing.

My build folder:
![screen shot 2015-08-21 at 09 33 07](https://cloud.githubusercontent.com/assets/3071376/9404555/92d602c8-47e8-11e5-9b6c-73a3a3f9382c.png)

My working Fireapp folder:
![screen shot 2015-08-21 at 09 33 03](https://cloud.githubusercontent.com/assets/3071376/9404576/b2f39610-47e8-11e5-8d6c-9a0c116914bc.png)

**Comment by hlb** [comment]
@encosion is `img` your image folder in `config.rb`?

**Comment by encosion** [comment]
@hlb http://localhost:24681 works for me, but I also get @selfthinker's 500 error messages on build

**Comment by encosion** [comment]
No, so you have a sense of context, my Fireapp folder looks something like this:
![screen shot 2015-08-21 at 09 44 52](https://cloud.githubusercontent.com/assets/3071376/9404672/5e7a11d0-47e9-11e5-873e-d6929df76e61.png)

My `config.rg` has a line like this:
`images_dir = "_assets/img" # by Fire.app`

The `img` folder I'm talking about is more of a tempoary thing that applies only to one of the subfolders and not the entire Fireapp build (odd use case perhaps?)

**Comment by hlb** [comment]
@encosion if you do not put files in `img` into your `_assets/img`, they will not generate into build folders :)

**Comment by encosion** [comment]
Thanks. Currently the entire `_assets/img` folder is missing from my build folder anyway though -- I'm assuming this is related to the aforementioned 500 message?

**Comment by hlb** [comment]
@encosion I believe there is some other issues. Would you mind to send me a copy of your project folder?

![test-case](https://cloud.githubusercontent.com/assets/4609/9405026/da17d114-4826-11e5-99be-477e7d43cc1d.png)

**Comment by hlb** [comment]
@encosion please zip and send to fireapp@kkbox.com if it is convenient to you.

**Comment by hlb** [comment]
@encosion's issue fixed by remove `layout.liquid`:)

**Comment by encosion** [comment]
FYI @hlb spotted a stray `.liquid` file in the root of my Fireapp folder, this was causing the 500 error. Issue solved! Thanks!

**Comment by selfthinker** [comment]
FYI, @encosion and me are colleagues and we were working on the same project and were having the same problem. So, this means this issue can be closed.
Thanks!

**Comment by hlb** [comment]
great! :)
